@ECHO off
SETLOCAL
SET "OPENCODE_ROOT=D:\codex\tools\opencode-home"
SET "NODE_ROOT=D:\codex\tools\node-v22.22.1-win-x64"
SET "OPENCODE_STATE_ROOT=D:\codex\oi-state-opencode"
IF DEFINED OPENCODE_STATE_ROOT_OVERRIDE SET "OPENCODE_STATE_ROOT=%OPENCODE_STATE_ROOT_OVERRIDE%"
SET "OPENCODE_WORKSPACE=D:\codex\opencode-workspace"
IF DEFINED OPENCODE_WORKSPACE_OVERRIDE SET "OPENCODE_WORKSPACE=%OPENCODE_WORKSPACE_OVERRIDE%"
SET "USERPROFILE=%OPENCODE_STATE_ROOT%\userprofile"
SET "HOME=%OPENCODE_STATE_ROOT%\userprofile"
SET "XDG_DATA_HOME=%OPENCODE_STATE_ROOT%\xdg"
IF NOT EXIST "%USERPROFILE%" mkdir "%USERPROFILE%" >nul 2>&1
IF NOT EXIST "%XDG_DATA_HOME%" mkdir "%XDG_DATA_HOME%" >nul 2>&1
IF NOT EXIST "%OPENCODE_WORKSPACE%" mkdir "%OPENCODE_WORKSPACE%" >nul 2>&1
PowerShell -ExecutionPolicy Bypass -File "D:\codex\opencode-state-guard.ps1" -StateRoot "%OPENCODE_STATE_ROOT%" >nul 2>&1
IF NOT DEFINED HTTP_PROXY IF DEFINED OPENCODE_HTTP_PROXY SET "HTTP_PROXY=%OPENCODE_HTTP_PROXY%"
IF NOT DEFINED HTTPS_PROXY IF DEFINED OPENCODE_HTTPS_PROXY SET "HTTPS_PROXY=%OPENCODE_HTTPS_PROXY%"
IF NOT DEFINED ALL_PROXY IF DEFINED OPENCODE_ALL_PROXY SET "ALL_PROXY=%OPENCODE_ALL_PROXY%"
IF NOT DEFINED NO_PROXY SET "NO_PROXY=127.0.0.1,localhost"
SET "PATH=%NODE_ROOT%;%PATH%"
IF DEFINED OPENCODE_FAST_WORKSPACE SET "OPENCODE_WORKSPACE=%OPENCODE_FAST_WORKSPACE%"
IF "%~1"=="" (
  CALL "%OPENCODE_ROOT%\opencode.cmd" "%OPENCODE_WORKSPACE%"
) ELSE (
  CALL "%OPENCODE_ROOT%\opencode.cmd" %*
)
