from __future__ import annotations

import argparse
import textwrap
from pathlib import Path

BOOT_ASM = textwrap.dedent(
    """
    [bits 32]
    global start
    extern kernel_main

    section .multiboot
    align 4
    dd 0x1BADB002
    dd 0x00000003
    dd -(0x1BADB002 + 0x00000003)

    section .text
    start:
        cli
        mov esp, stack_top
        call kernel_main
    .hang:
        hlt
        jmp .hang

    section .bss
    align 16
    stack_bottom:
        resb 16384
    stack_top:
    """
).strip() + "\n"

KERNEL_C = textwrap.dedent(
    """
    #include <stdint.h>

    static volatile uint16_t* const VGA = (uint16_t*)0xB8000;
    static uint16_t cursor = 0;

    static void write_char(char ch, uint8_t color) {
        VGA[cursor++] = ((uint16_t)color << 8) | (uint8_t)ch;
    }

    static void write_text(const char* text, uint8_t color) {
        while (*text) {
            if (*text == '\n') {
                cursor += 80 - (cursor % 80);
            } else {
                write_char(*text, color);
            }
            ++text;
        }
    }

    void kernel_main(void) {
        write_text("ToyOS booted in protected mode\\n", 0x0F);
        write_text("This is a teaching-grade kernel scaffold.\\n", 0x0A);
        write_text("Next steps: interrupts, paging, allocator, scheduler.\\n", 0x0E);
        for (;;) {
            __asm__ __volatile__("hlt");
        }
    }
    """
).strip() + "\n"

LINKER_LD = textwrap.dedent(
    """
    ENTRY(start)

    SECTIONS {
        . = 1M;

        .multiboot : {
            *(.multiboot)
        }

        .text : {
            *(.text*)
        }

        .rodata : {
            *(.rodata*)
        }

        .data : {
            *(.data*)
        }

        .bss : {
            *(.bss*)
            *(COMMON)
        }
    }
    """
).strip() + "\n"

MAKEFILE = textwrap.dedent(
    """
    ARCH := i686-elf
    AS := nasm
    CC := $(ARCH)-gcc
    LD := $(ARCH)-ld
    CFLAGS := -std=gnu99 -ffreestanding -O2 -Wall -Wextra
    LDFLAGS := -T linker.ld -nostdlib

    BUILD := build
    KERNEL := $(BUILD)/kernel.bin

    all: $(KERNEL)

    $(BUILD):
    	mkdir -p $(BUILD)

    $(BUILD)/boot.o: boot.asm | $(BUILD)
    	$(AS) -f elf32 boot.asm -o $@

    $(BUILD)/kernel.o: kernel.c | $(BUILD)
    	$(CC) $(CFLAGS) -c kernel.c -o $@

    $(KERNEL): $(BUILD)/boot.o $(BUILD)/kernel.o linker.ld
    	$(LD) $(LDFLAGS) -o $@ $(BUILD)/boot.o $(BUILD)/kernel.o

    run: $(KERNEL)
    	qemu-system-i386 -kernel $(KERNEL)

    clean:
    	rm -rf $(BUILD)
    """
).strip() + "\n"

README = textwrap.dedent(
    """
    # ToyOS

    This project is a tiny teaching-oriented x86 kernel scaffold generated by AI Command Console.

    ## What it contains

    - `boot.asm`: Multiboot header and bootstrap entry.
    - `kernel.c`: Minimal VGA text-mode kernel.
    - `linker.ld`: Kernel link layout.
    - `Makefile`: Build and run targets.

    ## Intended environment

    This project is meant for Linux or a local container sandbox.

    ## Build notes

    A real build typically needs a cross toolchain such as `i686-elf-gcc`, `i686-elf-ld`, `nasm`, and optionally `qemu-system-i386`.
    You can run `python3 orchestrator-mvp/tools/build_toy_os.py --target generated/toy-os-demo` to produce a machine-readable build report.

    ## Suggested next upgrades

    1. Add an interrupt descriptor table.
    2. Add a simple physical memory allocator.
    3. Add paging and heap support.
    4. Add a timer-driven scheduler.
    """
).strip() + "\n"

GITIGNORE = textwrap.dedent(
    """
    build/
    *.o
    *.bin
    *.iso
    build-report.json
    """
).strip() + "\n"


def write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a toy OS scaffold")
    parser.add_argument("--target", required=True, help="Target directory for the generated project")
    args = parser.parse_args()

    target = Path(args.target).resolve()
    target.mkdir(parents=True, exist_ok=True)

    write_file(target / "boot.asm", BOOT_ASM)
    write_file(target / "kernel.c", KERNEL_C)
    write_file(target / "linker.ld", LINKER_LD)
    write_file(target / "Makefile", MAKEFILE)
    write_file(target / "README.md", README)
    write_file(target / ".gitignore", GITIGNORE)

    print(f"Toy OS scaffold created at: {target}")
    print("Files:")
    for name in ["boot.asm", "kernel.c", "linker.ld", "Makefile", "README.md", ".gitignore"]:
        print(f"- {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
